// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/redhajuanda/komon/cache (interfaces: Cache)
//
// Generated by this command:
//
//	mockgen -destination=cacher_mock.go -package=qwery github.com/redhajuanda/komon/cache Cache
//

// Package qwery is a generated GoMock package.
package qwery

import (
	context "context"
	reflect "reflect"

	cache "github.com/redhajuanda/komon/cache"
	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCache) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacheMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCache)(nil).Close))
}

// Del mocks base method.
func (m *MockCache) Del(ctx context.Context, keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockCacheMockRecorder) Del(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCache)(nil).Del), varargs...)
}

// DeleteWithPattern mocks base method.
func (m *MockCache) DeleteWithPattern(ctx context.Context, pattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithPattern", ctx, pattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithPattern indicates an expected call of DeleteWithPattern.
func (mr *MockCacheMockRecorder) DeleteWithPattern(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithPattern", reflect.TypeOf((*MockCache)(nil).DeleteWithPattern), ctx, pattern)
}

// Exists mocks base method.
func (m *MockCache) Exists(ctx context.Context, keys ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exists", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCacheMockRecorder) Exists(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCache)(nil).Exists), varargs...)
}

// Get mocks base method.
func (m *MockCache) Get(ctx context.Context, key string, dest any, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(ctx, key, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), varargs...)
}

// GetInt mocks base method.
func (m *MockCache) GetInt(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInt indicates an expected call of GetInt.
func (mr *MockCacheMockRecorder) GetInt(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockCache)(nil).GetInt), ctx, key)
}

// GetMember mocks base method.
func (m *MockCache) GetMember(ctx context.Context, key string, dest any, opts ...cache.Option) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMember", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockCacheMockRecorder) GetMember(ctx, key, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockCache)(nil).GetMember), varargs...)
}

// GetString mocks base method.
func (m *MockCache) GetString(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetString indicates an expected call of GetString.
func (mr *MockCacheMockRecorder) GetString(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockCache)(nil).GetString), ctx, key)
}

// HGet mocks base method.
func (m *MockCache) HGet(ctx context.Context, key, field string, dest any, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, field, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HGet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HGet indicates an expected call of HGet.
func (mr *MockCacheMockRecorder) HGet(ctx, key, field, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, field, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGet", reflect.TypeOf((*MockCache)(nil).HGet), varargs...)
}

// HGetAll mocks base method.
func (m *MockCache) HGetAll(ctx context.Context, key string, dest any, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HGetAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HGetAll indicates an expected call of HGetAll.
func (mr *MockCacheMockRecorder) HGetAll(ctx, key, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGetAll", reflect.TypeOf((*MockCache)(nil).HGetAll), varargs...)
}

// HMGetPipelined mocks base method.
func (m *MockCache) HMGetPipelined(ctx context.Context, requests map[string]string, opts ...cache.Option) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, requests}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HMGetPipelined", varargs...)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HMGetPipelined indicates an expected call of HMGetPipelined.
func (mr *MockCacheMockRecorder) HMGetPipelined(ctx, requests any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, requests}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HMGetPipelined", reflect.TypeOf((*MockCache)(nil).HMGetPipelined), varargs...)
}

// HMSetPipelined mocks base method.
func (m *MockCache) HMSetPipelined(ctx context.Context, writes map[string][]*cache.DataSet, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, writes}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HMSetPipelined", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HMSetPipelined indicates an expected call of HMSetPipelined.
func (mr *MockCacheMockRecorder) HMSetPipelined(ctx, writes any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, writes}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HMSetPipelined", reflect.TypeOf((*MockCache)(nil).HMSetPipelined), varargs...)
}

// HSet mocks base method.
func (m *MockCache) HSet(ctx context.Context, key string, data []*cache.DataSet, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HSet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *MockCacheMockRecorder) HSet(ctx, key, data any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockCache)(nil).HSet), varargs...)
}

// Increment mocks base method.
func (m *MockCache) Increment(ctx context.Context, key string, opts ...cache.Option) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Increment", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Increment indicates an expected call of Increment.
func (mr *MockCacheMockRecorder) Increment(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockCache)(nil).Increment), varargs...)
}

// IncrementFixed mocks base method.
func (m *MockCache) IncrementFixed(ctx context.Context, key string, opts ...cache.Option) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IncrementFixed", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementFixed indicates an expected call of IncrementFixed.
func (mr *MockCacheMockRecorder) IncrementFixed(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFixed", reflect.TypeOf((*MockCache)(nil).IncrementFixed), varargs...)
}

// MGet mocks base method.
func (m *MockCache) MGet(ctx context.Context, keys []string, dest any, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, keys, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// MGet indicates an expected call of MGet.
func (mr *MockCacheMockRecorder) MGet(ctx, keys, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, keys, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockCache)(nil).MGet), varargs...)
}

// Set mocks base method.
func (m *MockCache) Set(ctx context.Context, key string, value any, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, value}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(ctx, key, value any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, value}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), varargs...)
}

// SetMember mocks base method.
func (m *MockCache) SetMember(ctx context.Context, key string, data []*cache.DataSet, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetMember", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMember indicates an expected call of SetMember.
func (mr *MockCacheMockRecorder) SetMember(ctx, key, data any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMember", reflect.TypeOf((*MockCache)(nil).SetMember), varargs...)
}

// SetMultiple mocks base method.
func (m *MockCache) SetMultiple(ctx context.Context, data []*cache.DataSet, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetMultiple", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMultiple indicates an expected call of SetMultiple.
func (mr *MockCacheMockRecorder) SetMultiple(ctx, data any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMultiple", reflect.TypeOf((*MockCache)(nil).SetMultiple), varargs...)
}

// UnmarshalValue mocks base method.
func (m *MockCache) UnmarshalValue(raw []byte, dest any, opts ...cache.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{raw, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnmarshalValue", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalValue indicates an expected call of UnmarshalValue.
func (mr *MockCacheMockRecorder) UnmarshalValue(raw, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{raw, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalValue", reflect.TypeOf((*MockCache)(nil).UnmarshalValue), varargs...)
}
